### ISSUE TITLE
Actuator (프로덕션환경 준비)

### ISSUE THREAD

**Issue by bmworld** [bmworld/inflearn-java-spring-roadmap#7]
# 목표
- 프로덕션환경에서 WAS 관리/유지보수하기위한 필요기능을 활용해보자.

# 세팅
```gradle
    implementation 'org.springframework.boot:spring-boot-starter-actuator' //actuator 추가
```

```yml
management:
  endpoints:
    web:
      exposure:
        include: "*" # "*": 엑츄에이터 모든 Endpoint(기능) 활성화

```
